title: Github's Polatouche's Blog
author: Antoine Polatouche
email: antoine@jabron.com
description: > # this means to ignore newlines until "baseurl:"
  Just an awesome blog by the famous Polatouche

# social links
twitter_username: @APolatouche
github_username:  Polatouche

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
